require: rubocop-rspec

inherit_mode:
  merge:
    - Exclude

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1
  Exclude:
    - example/app/assets/**/*
    - example/bin/*
    - example/db/*schema.rb
    - example/log/**/*
    - example/public/**/*
    - example/storage/**/*


Layout/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Metrics/ClassLength:
  Max: 200

RSpec/NestedGroups:
  Max: 5

RSpec/ExampleLength:
  Max: 15

RSpec/NamedSubject:
  Enabled: false
