require: rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7

Layout/LineLength:
  Max: 120

Metrics/ClassLength:
  Max: 200

RSpec/NestedGroups:
  Max: 5

RSpec/ExampleLength:
  Max: 15

RSpec/NamedSubject:
  Enabled: false
