require: rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0
  Exclude:
    - 'db/schema.rb'
    - 'example/bin/*'
    - 'example/vendor/*'

Layout/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Metrics/ClassLength:
  Max: 200

RSpec/NestedGroups:
  Max: 5

RSpec/ExampleLength:
  Max: 15

RSpec/NamedSubject:
  Enabled: false
